---
- apt: name={{item}} state=latest
  with_items:
  - libpcre3
  - libpcre3-dev
  - libssl-dev
  - openssl

- group: name=nginx state=present

- user: name=nginx group=nginx shell=/bin/bash createhome=yes state=present

- copy: src=etc_security_limits.d_nginx.conf dest=/etc/security/limits.d/nginx.conf

- file: dest=/usr/local/src owner=root group=root state=directory

- get_url: url=http://nginx.org/download/nginx-{{nginx__version}}.tar.gz 
          dest=/usr/local/src/nginx-{{nginx__version}}.tar.gz

- command: tar -xzf /usr/local/src/nginx-{{nginx__version}}.tar.gz -C /usr/local/src 
           creates=/usr/local/src/nginx-{{nginx__version}}

- command: ./configure --with-http_ssl_module --with-http_spdy_module --prefix=/usr/local/nginx-{{nginx__version}} --conf-path=/etc/nginx/nginx.conf  --user=nginx --group=nginx 
           chdir=/usr/local/src/nginx-{{nginx__version}} 
           creates=/usr/local/src/nginx-{{nginx__version}}/Makefile
  register: configured

- command: make chdir=/usr/local/src/nginx-{{nginx__version}}
  when: configured.changed

- command: make install chdir=/usr/local/src/nginx-{{nginx__version}}
  when: configured.changed
  notify: 
  - restart nginx

- file: name=/usr/local/nginx-{{nginx__version}} owner=nginx group=nginx state=directory recurse=yes

- file: name=/var/log/nginx owner=nginx group=nginx state=directory

- file: path=/etc/nginx/{{item}} state=directory owner=nginx group=nginx mode=0755
  with_items:
  - sites-available
  - sites-enabled

- file: name=/etc/nginx owner=nginx group=nginx state=directory recurse=yes

- copy: src=etc_nginx_nginx.conf dest=/etc/nginx/nginx.conf owner=nginx group=nginx mode=0644
  notify: 
  - restart nginx
  tags:
  - config

- copy: src=etc_init.d_nginx dest=/etc/init.d/nginx owner=root group=root mode=0755
  notify: 
  - restart nginx

- command: update-rc.d nginx defaults 20 creates=/etc/rc2.d/S20nginx

# stop current service, in case it's an old version
- service: name=nginx state=stopped
  notify:
  - restart nginx

- file: src=/usr/local/nginx-{{nginx__version}} dest=/usr/local/nginx state=link

- file: path=/usr/local/nginx-{{item}} state=absent
  with_items: $nginx__previous_versions
  tags:
  - clean

- file: path=/usr/local/src/nginx-{{item}} state=absent
  with_items: $nginx__previous_versions
  tags:
  - clean

- file: path=/usr/local/src/nginx-{{item}}.tar.gz state=absent
  with_items: $nginx__previous_versions
  tags:
  - clean
